apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-external-secret
  namespace: openshift-operators
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: eso-secret-store
    kind: ClusterSecretStore
  target:
    name: example-secret
    creationPolicy: Owner
  data:
  - secretKey: example
    remoteRef:
      key: secret/github-pat